version: "3.8"

networks:
  my_network:

services:
  # General
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # RabbitMQ server port
      - "15672:15672" # RabbitMQ management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - my_network
  
  # MySQL server
  mysqlserver:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

  # Supplier
  supplier:
    image: suppliermanagement_app_asp:0.4
    build:
      context: .
      dockerfile: ./SupplierDockerfile
    ports:
      - "5300:5300"
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBITMQ_HOSTNAME=rabbitmq
      - ASPNETCORE_URLS=http://+:5300 
    volumes:
      - dotnet_supplier_data:/app
    networks:
      - my_network

  # Order
  order:
    image: ordermanagement_app:0.3
    build:
      context: .
      dockerfile: ./OrderDockerfile
    ports:
      - "5220:5219"
      - "8081:8080"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBITMQ_HOSTNAME=rabbitmq
    volumes:
      - dotnet_order_data:/app
    networks:
      - my_network

  # Tracking
  tracking:
    image: trackingmanagement_app:0.3
    build:
      context: .
      dockerfile: ./TrackingDockerfile
    ports:
      - "5308:5308"
      - "8089:8080"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBITMQ_HOSTNAME=rabbitmq
      - ASPNETCORE_URLS=http://+:5308
    volumes:
      - dotnet_tracking_data:/app
    networks:
      - my_network

volumes:
  rabbitmq_data:
  mysql_data:
  mongo_data:
  dotnet_supplier_data:
  dotnet_order_data:
  dotnet_tracking_data:
