version: '3.8'

networks:
  my_network: 

services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # RabbitMQ server port
      - "15672:15672" # RabbitMQ management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - my_network

  dotnet_app:
    image: dotnetapp:0.3
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5219:5219"
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOSTNAME=rabbitmq
    volumes:
      - dotnet_app_data:/app
    networks:
      - my_network

volumes:
  mysql_data:
  mongo_data:
  dotnet_app_data:
  rabbitmq_data: