version: "3.8"

networks:
  my_network:

services:
  # general
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # RabbitMQ server port
      - "15672:15672" # RabbitMQ management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - my_network

  # supplier
  supplier:
    image: dotnetapp:0.3
    build:
      context: .
      dockerfile: ./SupplierDockerfile
    ports:
      - "5219:5219"
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBITMQ_HOSTNAME=rabbitmq
    volumes:
      - dotnet_supplier_data:/app
    networks:
      - my_network

  suppliermysql:
    image: mysql:latest
    container_name: mysql_supplier_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mysupplierdatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_supplier_data:/var/lib/mysql
    networks:
      - my_network

  suppliermongodb:
    image: mongo:latest
    container_name: mongodb_supplier_container
    ports:
      - "28000:27017"
    volumes:
      - mongo_supplier_data:/data/db
    networks:
      - my_network

  # order
  order:
    image: ordermanagement_app:0.3
    build:
      context: .
      dockerfile: ./OrderManagement/OrderDockerfile
    ports:
      - "5220:5219"
      - "8081:8080"
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - RABBITMQ_HOSTNAME=rabbitmq
    volumes:
      - dotnet_order_data:/app
    networks:
      - my_network

  ordermysql:
    image: mysql:latest
    container_name: mysql_order_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: myorderdatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_order_data:/var/lib/mysql
    networks:
      - my_network

  ordermongodb:
    image: mongo:latest
    container_name: mongodb_order_container
    ports:
      - "28001:27017"
    volumes:
      - mongo_order_data:/data/db
    networks:
      - my_network

volumes:
  # supplier
  dotnet_supplier_data:
  mysql_supplier_data:
  mongo_supplier_data:
  # order
  dotnet_order_data:
  mysql_order_data:
  mongo_order_data:
  # general
  rabbitmq_data:
