version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"   # RabbitMQ server port
      - "15672:15672" # RabbitMQ management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql



  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "28000:27017"
    volumes:
      - mongo_data:/data/db


  dotnet_app:
    image: ballcomsolution:latest
    container_name: supplier_rest
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq_container
      - RABBITMQ_PORT=5672
    volumes:
      - dotnet_app_data:/app

volumes:
  rabbitmq_data:
  mysql_data:
  mongo_data:
  dotnet_app_data:
