version: '3.8'

networks:
  my_network:

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "28000:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_container
    ports:
      - "5672:5672"   # RabbitMQ server port
      - "15672:15672" # RabbitMQ management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - my_network

  dotnet_app:
    image: supplierservice:test
    container_name: supplier_rest
    ports:
      - "5219:5219"
      - "8080:8080"
    depends_on:
      - mysql
      - mongodb
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    volumes:
      - dotnet_app_data:/app
    networks:
      - my_network

volumes:
  mysql_data:
  mongo_data:
  dotnet_app_data:
  rabbitmq_data: